# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Publish

on:
  push:
    branches: [socket-proxed]
  pull_request:
    branches: [socket-proxed]

jobs:
  
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: "@HiImGiovi"

      # Install all prerequisites
      - run: npm install

      # Run the tests
      - run: npm publish
        env: 
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
